
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jai shree ram
 */
public class ForgeSalary extends javax.swing.JFrame {

    /**
     * Creates new form Make_Salary
     */
    public ForgeSalary() {
        initComponents();
        payable_amt.setText("12000");
        basic_sal.setText("0");
        hra.setText("0");
        cca.setText("0");
        conveyance.setText("0");
        medical_allowance.setText("0");
        ta_da.setText("0");
        special_allowance.setText("0");
        extra_payable.setText("0");
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        regd_id = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        regd_id2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        regd_id1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        stu_name = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        basic_sal = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        hra = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        cca = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        ta_da = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        medical_allowance = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        extra_payable = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        special_allowance = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        conveyance = new javax.swing.JTextField();
        payable_amt = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton34 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        pf = new javax.swing.JTextField();
        esic = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        total_basic_deduction = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        pt = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        advance = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        special_deduction = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        other_deduction = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        total_attendence = new javax.swing.JTextField();
        present_days = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        absent_days = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        absent_amt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        present_amt = new javax.swing.JTextField();
        extra_days = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        total_payable = new javax.swing.JTextField();
        basic_deduction = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jTextField47 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        absent_deduction = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        total_deduction = new javax.swing.JTextField();
        basic_sal14 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)), "Forge Salary", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)), "Enter Teacher Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel17.setText("Employ ID:-");

        regd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regd_idActionPerformed(evt);
            }
        });
        regd_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regd_idKeyReleased(evt);
            }
        });

        jLabel20.setText("Teacher No. :-");

        regd_id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regd_id2ActionPerformed(evt);
            }
        });
        regd_id2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regd_id2KeyReleased(evt);
            }
        });

        jLabel24.setText("Date of Joining:-");

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel19.setText("Department :-");

        regd_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regd_id1ActionPerformed(evt);
            }
        });
        regd_id1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regd_id1KeyReleased(evt);
            }
        });

        jLabel23.setText("Teacher Name:-");

        stu_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_nameActionPerformed(evt);
            }
        });

        jLabel59.setText("Designation:-");

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Teaching", "Non Teaching" }));
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regd_id, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regd_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regd_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stu_name, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(regd_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(regd_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(regd_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel59)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)), "Basic Salary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel21.setText("Basic Salary:-");

        basic_sal.setEditable(false);
        basic_sal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                basic_salMouseClicked(evt);
            }
        });
        basic_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_salActionPerformed(evt);
            }
        });
        basic_sal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                basic_salFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                basic_salFocusLost(evt);
            }
        });
        basic_sal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                basic_salKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                basic_salKeyTyped(evt);
            }
        });

        jLabel53.setText("H.R.A :-");

        hra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hraActionPerformed(evt);
            }
        });
        hra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hraKeyTyped(evt);
            }
        });

        jLabel54.setText("C.C.A :-");

        jLabel55.setText("Conveyance :-");

        cca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccaActionPerformed(evt);
            }
        });
        cca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ccaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ccaKeyTyped(evt);
            }
        });

        jLabel56.setText("Special Allowance:-");

        ta_da.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ta_daMouseClicked(evt);
            }
        });
        ta_da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta_daActionPerformed(evt);
            }
        });
        ta_da.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ta_daFocusGained(evt);
            }
        });
        ta_da.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ta_daKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ta_daKeyTyped(evt);
            }
        });

        jLabel57.setText("Medical Allowance :-");

        medical_allowance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medical_allowanceMouseClicked(evt);
            }
        });
        medical_allowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medical_allowanceActionPerformed(evt);
            }
        });
        medical_allowance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                medical_allowanceFocusGained(evt);
            }
        });
        medical_allowance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                medical_allowanceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                medical_allowanceKeyTyped(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel58.setText("Total Payable Amt :-");

        extra_payable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extra_payableMouseClicked(evt);
            }
        });
        extra_payable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extra_payableActionPerformed(evt);
            }
        });
        extra_payable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                extra_payableFocusGained(evt);
            }
        });
        extra_payable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                extra_payableKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                extra_payableKeyTyped(evt);
            }
        });

        jLabel22.setText("TA/DA:-");

        special_allowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                special_allowanceActionPerformed(evt);
            }
        });
        special_allowance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                special_allowanceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                special_allowanceKeyTyped(evt);
            }
        });

        jLabel60.setText("Extra Payable :-");

        conveyance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conveyanceActionPerformed(evt);
            }
        });
        conveyance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                conveyanceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                conveyanceKeyTyped(evt);
            }
        });

        payable_amt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        payable_amt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        payable_amt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                payable_amtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel21))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(conveyance, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel57))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(basic_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(special_allowance, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel60)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extra_payable, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hra, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medical_allowance, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ta_da, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payable_amt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(basic_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(hra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(cca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medical_allowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57)
                    .addComponent(conveyance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(jLabel22)
                    .addComponent(ta_da, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payable_amt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel56)
                        .addComponent(special_allowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel60)
                        .addComponent(extra_payable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel58)))
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 0)));

        jButton34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton34.setForeground(new java.awt.Color(51, 51, 255));
        jButton34.setText("Save");

        jButton36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton36.setForeground(new java.awt.Color(51, 51, 255));
        jButton36.setText("Delete");

        jButton35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton35.setForeground(new java.awt.Color(51, 51, 255));
        jButton35.setText("Modify");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton37.setForeground(new java.awt.Color(51, 51, 255));
        jButton37.setText("Print Slip");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)), "Basic Deduction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel25.setText("Provided Fund(P.F) :-");

        pf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfMouseClicked(evt);
            }
        });
        pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfActionPerformed(evt);
            }
        });
        pf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfFocusGained(evt);
            }
        });
        pf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfKeyTyped(evt);
            }
        });

        esic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esicActionPerformed(evt);
            }
        });
        esic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                esicKeyTyped(evt);
            }
        });

        jLabel62.setText("P.T :-");

        total_basic_deduction.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        total_basic_deduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_basic_deductionActionPerformed(evt);
            }
        });

        jLabel63.setText("E.S.I.C :-");

        pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptActionPerformed(evt);
            }
        });
        pt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ptKeyTyped(evt);
            }
        });

        jLabel64.setText("Special Deduction :-");

        jLabel65.setText("Other Deduction :-");

        advance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advanceMouseClicked(evt);
            }
        });
        advance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanceActionPerformed(evt);
            }
        });
        advance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                advanceFocusGained(evt);
            }
        });
        advance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                advanceKeyTyped(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setText("Total Basic Deduction :-");

        special_deduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                special_deductionActionPerformed(evt);
            }
        });
        special_deduction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                special_deductionKeyTyped(evt);
            }
        });

        jLabel67.setText("Advace :-");

        other_deduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                other_deductionActionPerformed(evt);
            }
        });
        other_deduction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                other_deductionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel65))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(other_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63)
                            .addComponent(jLabel67))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel64))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(esic, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel66)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(special_deduction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(pt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total_basic_deduction, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63))
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65)
                    .addComponent(other_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67)
                    .addComponent(jLabel64)
                    .addComponent(special_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(total_basic_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)), "Attendence Deduction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel27.setText("Total Attendence :-");

        total_attendence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total_attendenceMouseClicked(evt);
            }
        });
        total_attendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_attendenceActionPerformed(evt);
            }
        });
        total_attendence.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                total_attendenceFocusGained(evt);
            }
        });
        total_attendence.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total_attendenceKeyTyped(evt);
            }
        });

        present_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                present_daysActionPerformed(evt);
            }
        });
        present_days.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                present_daysKeyTyped(evt);
            }
        });

        jLabel68.setText("Absent Days :-");

        jTextField44.setEditable(false);
        jTextField44.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField44ActionPerformed(evt);
            }
        });

        jLabel69.setText(" Present Days:-");

        absent_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absent_daysActionPerformed(evt);
            }
        });
        absent_days.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                absent_daysKeyTyped(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setText("Absent's Deduction :-");

        jLabel28.setText("Absent Amt. :-");

        absent_amt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absent_amtMouseClicked(evt);
            }
        });
        absent_amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absent_amtActionPerformed(evt);
            }
        });
        absent_amt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                absent_amtFocusGained(evt);
            }
        });
        absent_amt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                absent_amtKeyTyped(evt);
            }
        });

        jLabel29.setText("Present Amt. :-");

        present_amt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                present_amtMouseClicked(evt);
            }
        });
        present_amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                present_amtActionPerformed(evt);
            }
        });
        present_amt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                present_amtFocusGained(evt);
            }
        });
        present_amt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                present_amtKeyTyped(evt);
            }
        });

        extra_days.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extra_daysMouseClicked(evt);
            }
        });
        extra_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extra_daysActionPerformed(evt);
            }
        });
        extra_days.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                extra_daysFocusGained(evt);
            }
        });
        extra_days.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                extra_daysKeyTyped(evt);
            }
        });

        jLabel30.setText("Extra Days :-");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(11, 11, 11)
                                .addComponent(total_attendence, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(extra_days, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel69))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(present_days, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(present_amt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel68)
                            .addComponent(jLabel28))
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel72)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(absent_days, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(absent_amt)
                    .addComponent(jTextField44))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(total_attendence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(present_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(absent_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(absent_amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(present_amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(extra_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)), "Final Salary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel31.setText("Total Payable  :-");

        total_payable.setEditable(false);
        total_payable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total_payableMouseClicked(evt);
            }
        });
        total_payable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_payableActionPerformed(evt);
            }
        });
        total_payable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                total_payableFocusGained(evt);
            }
        });
        total_payable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total_payableKeyTyped(evt);
            }
        });

        basic_deduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_deductionActionPerformed(evt);
            }
        });
        basic_deduction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                basic_deductionKeyTyped(evt);
            }
        });

        jLabel70.setText("Absent Deduction :-");

        jTextField47.setEditable(false);
        jTextField47.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField47ActionPerformed(evt);
            }
        });

        jLabel71.setText("Basic Deduction :-");

        absent_deduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absent_deductionActionPerformed(evt);
            }
        });
        absent_deduction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                absent_deductionKeyTyped(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel73.setText("Net Payable Salary  :-");

        jLabel33.setText("Total Deduction :-");

        total_deduction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total_deductionMouseClicked(evt);
            }
        });
        total_deduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_deductionActionPerformed(evt);
            }
        });
        total_deduction.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                total_deductionFocusGained(evt);
            }
        });

        basic_sal14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                basic_sal14MouseClicked(evt);
            }
        });
        basic_sal14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_sal14ActionPerformed(evt);
            }
        });
        basic_sal14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                basic_sal14FocusGained(evt);
            }
        });

        jLabel34.setText("Other Deduction :-");

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setText("Total Payable   -   Total Deduction     =");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(27, 27, 27)
                                .addComponent(total_payable, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(basic_sal14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel71))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basic_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel70)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel74)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel73)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(absent_deduction, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jTextField47))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(total_payable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basic_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel70)
                    .addComponent(absent_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(total_deduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(basic_sal14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73)
                    .addComponent(jLabel74))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 803, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regd_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regd_idActionPerformed

    private void regd_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regd_idKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_regd_idKeyReleased

    private void regd_id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regd_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regd_id2ActionPerformed

    private void regd_id2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regd_id2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_regd_id2KeyReleased

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void regd_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regd_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regd_id1ActionPerformed

    private void regd_id1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regd_id1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_regd_id1KeyReleased

    private void stu_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_nameActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void basic_salMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_salMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_basic_salMouseClicked

    private void basic_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_salActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_basic_salActionPerformed

    private void basic_salFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_basic_salFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_basic_salFocusGained

    private void hraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hraActionPerformed

    private void ccaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccaActionPerformed

    private void ta_daMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_daMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ta_daMouseClicked

    private void ta_daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta_daActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ta_daActionPerformed

    private void ta_daFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ta_daFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ta_daFocusGained

    private void medical_allowanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medical_allowanceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_medical_allowanceMouseClicked

    private void medical_allowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medical_allowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medical_allowanceActionPerformed

    private void medical_allowanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_medical_allowanceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_medical_allowanceFocusGained

    private void extra_payableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extra_payableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_extra_payableMouseClicked

    private void extra_payableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extra_payableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extra_payableActionPerformed

    private void extra_payableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_extra_payableFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_extra_payableFocusGained

    private void special_allowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_special_allowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_special_allowanceActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void conveyanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conveyanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conveyanceActionPerformed

    private void pfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pfMouseClicked

    private void pfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfActionPerformed

    private void pfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pfFocusGained

    private void esicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esicActionPerformed

    private void total_basic_deductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_basic_deductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_basic_deductionActionPerformed

    private void ptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptActionPerformed

    private void advanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advanceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_advanceMouseClicked

    private void advanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advanceActionPerformed

    private void advanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_advanceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_advanceFocusGained

    private void special_deductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_special_deductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_special_deductionActionPerformed

    private void other_deductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_other_deductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_other_deductionActionPerformed

    private void total_attendenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_attendenceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_total_attendenceMouseClicked

    private void total_attendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_attendenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_attendenceActionPerformed

    private void total_attendenceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_attendenceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_total_attendenceFocusGained

    private void present_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_present_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_present_daysActionPerformed

    private void jTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField44ActionPerformed

    private void absent_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absent_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absent_daysActionPerformed

    private void absent_amtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absent_amtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_absent_amtMouseClicked

    private void absent_amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absent_amtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absent_amtActionPerformed

    private void absent_amtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_absent_amtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_absent_amtFocusGained

    private void present_amtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_present_amtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_present_amtMouseClicked

    private void present_amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_present_amtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_present_amtActionPerformed

    private void present_amtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_present_amtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_present_amtFocusGained

    private void extra_daysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extra_daysMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_extra_daysMouseClicked

    private void extra_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extra_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extra_daysActionPerformed

    private void extra_daysFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_extra_daysFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_extra_daysFocusGained

    private void total_payableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_payableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_total_payableMouseClicked

    private void total_payableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_payableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_payableActionPerformed

    private void total_payableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_payableFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_total_payableFocusGained

    private void basic_deductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_deductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basic_deductionActionPerformed

    private void jTextField47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField47ActionPerformed

    private void absent_deductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absent_deductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absent_deductionActionPerformed

    private void total_deductionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_deductionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_total_deductionMouseClicked

    private void total_deductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_deductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_deductionActionPerformed

    private void total_deductionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_deductionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_total_deductionFocusGained

    private void basic_sal14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_sal14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_basic_sal14MouseClicked

    private void basic_sal14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_sal14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basic_sal14ActionPerformed

    private void basic_sal14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_basic_sal14FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_basic_sal14FocusGained

    private void basic_salKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basic_salKeyReleased
       
              if(basic_sal.getText().isEmpty())
                  basic_sal.setText("0");
              
        int a = Integer.parseInt(basic_sal.getText());
       int b= Integer.parseInt(hra.getText());
       int c = Integer.parseInt(cca.getText());
       int d= Integer.parseInt(conveyance.getText());
       int e = Integer.parseInt(medical_allowance.getText());
       int f= Integer.parseInt(ta_da.getText());
       int g = Integer.parseInt(special_allowance.getText());
       int h= Integer.parseInt(extra_payable.getText());
       
       int add= a+b+c+d+e+f+g+h;
       String result=String.valueOf(add);
       payable_amt.setText(result);
        
       
    }//GEN-LAST:event_basic_salKeyReleased

    private void hraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hraKeyReleased
       
                       if(hra.getText().isEmpty())
            hra.setText("0");
        
        int a = Integer.parseInt(basic_sal.getText());
       int b= Integer.parseInt(hra.getText());
       int c = Integer.parseInt(cca.getText());
       int d= Integer.parseInt(conveyance.getText());
       int e = Integer.parseInt(medical_allowance.getText());
       int f= Integer.parseInt(ta_da.getText());
       int g = Integer.parseInt(special_allowance.getText());
       int h= Integer.parseInt(extra_payable.getText());
       
      int add= a+b+c+d+e+f+g+h;
       String result=String.valueOf(add);
       payable_amt.setText(result);
       

    }//GEN-LAST:event_hraKeyReleased

    private void ccaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccaKeyReleased
       
               if(cca.getText().isEmpty())
            cca.setText("0");

        int a = Integer.parseInt(basic_sal.getText());
       int b= Integer.parseInt(hra.getText());
       int c = Integer.parseInt(cca.getText());
       int d= Integer.parseInt(conveyance.getText());
       int e = Integer.parseInt(medical_allowance.getText());
       int f= Integer.parseInt(ta_da.getText());
       int g = Integer.parseInt(special_allowance.getText());
       int h= Integer.parseInt(extra_payable.getText());
       
       int add= a+b+c+d+e+f+g+h;
       String result=String.valueOf(add);
       payable_amt.setText(result);

   
    }//GEN-LAST:event_ccaKeyReleased

    private void conveyanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conveyanceKeyReleased
      
        if(conveyance.getText().isEmpty())
            conveyance.setText("0");
        
       int a = Integer.parseInt(basic_sal.getText());
       int b= Integer.parseInt(hra.getText());
       int c = Integer.parseInt(cca.getText());
       int d= Integer.parseInt(conveyance.getText());
       int e = Integer.parseInt(medical_allowance.getText());
       int f= Integer.parseInt(ta_da.getText());
       int g = Integer.parseInt(special_allowance.getText());
       int h= Integer.parseInt(extra_payable.getText());
       
      int add= a+b+c+d+e+f+g+h;
       String result=String.valueOf(add);
       payable_amt.setText(result);
    }//GEN-LAST:event_conveyanceKeyReleased

    private void medical_allowanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medical_allowanceKeyReleased
      
        if(medical_allowance.getText().isEmpty())
            medical_allowance.setText("0");
        
        int a = Integer.parseInt(basic_sal.getText());
       int b= Integer.parseInt(hra.getText());
       int c = Integer.parseInt(cca.getText());
       int d= Integer.parseInt(conveyance.getText());
       int e = Integer.parseInt(medical_allowance.getText());
       int f= Integer.parseInt(ta_da.getText());
       int g = Integer.parseInt(special_allowance.getText());
       int h= Integer.parseInt(extra_payable.getText());
       
       int add= a+b+c+d+e+f+g+h;
       String result=String.valueOf(add);
       payable_amt.setText(result);
    }//GEN-LAST:event_medical_allowanceKeyReleased

    private void ta_daKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ta_daKeyReleased
       
            if(ta_da.getText().isEmpty())
                ta_da.setText("0");
            
        
        int a = Integer.parseInt(basic_sal.getText());
       int b= Integer.parseInt(hra.getText());
       int c = Integer.parseInt(cca.getText());
       int d= Integer.parseInt(conveyance.getText());
       int e = Integer.parseInt(medical_allowance.getText());
       int f= Integer.parseInt(ta_da.getText());
       int g = Integer.parseInt(special_allowance.getText());
       int h= Integer.parseInt(extra_payable.getText());
       
       int add= a+b+c+d+e+f+g+h;
       String result=String.valueOf(add);
       payable_amt.setText(result);
    }//GEN-LAST:event_ta_daKeyReleased

    private void special_allowanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_special_allowanceKeyReleased
       
                if(special_allowance.getText().isEmpty())
                    special_allowance.setText("0");
        
        int a = Integer.parseInt(basic_sal.getText());
       int b= Integer.parseInt(hra.getText());
       int c = Integer.parseInt(cca.getText());
       int d= Integer.parseInt(conveyance.getText());
       int e = Integer.parseInt(medical_allowance.getText());
       int f= Integer.parseInt(ta_da.getText());
       int g = Integer.parseInt(special_allowance.getText());
       int h= Integer.parseInt(extra_payable.getText());
           int add= a+b+c+d+e+f+g+h;
       String result=String.valueOf(add);
       payable_amt.setText(result);
    }//GEN-LAST:event_special_allowanceKeyReleased

    private void extra_payableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extra_payableKeyReleased
        
            if(extra_payable.getText().isEmpty())
                extra_payable.setText("0");
        
        int a = Integer.parseInt(basic_sal.getText());
       int b= Integer.parseInt(hra.getText());
       int c = Integer.parseInt(cca.getText());
       int d= Integer.parseInt(conveyance.getText());
       int e = Integer.parseInt(medical_allowance.getText());
       int f= Integer.parseInt(ta_da.getText());
       int g = Integer.parseInt(special_allowance.getText());
       int h= Integer.parseInt(extra_payable.getText());
       
       int add= a+b+c+d+e+f+g+h;
       String result=String.valueOf(add);
       payable_amt.setText(result);
    }//GEN-LAST:event_extra_payableKeyReleased

    private void basic_salKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basic_salKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_basic_salKeyTyped

    private void hraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hraKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_hraKeyTyped

    private void ccaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccaKeyTyped
      char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_ccaKeyTyped

    private void conveyanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conveyanceKeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_conveyanceKeyTyped

    private void medical_allowanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medical_allowanceKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_medical_allowanceKeyTyped

    private void ta_daKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ta_daKeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_ta_daKeyTyped

    private void special_allowanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_special_allowanceKeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_special_allowanceKeyTyped

    private void extra_payableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extra_payableKeyTyped
      char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_extra_payableKeyTyped

    private void payable_amtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payable_amtKeyReleased
             int a = Integer.parseInt(payable_amt.getText());
             int b= Integer.parseInt(extra_days.getText());
             int c= Integer.parseInt(basic_sal.getText());
                      int calDays=((c/30) * b);
                    int finalPayable= (calDays + a);
                    String result=String.valueOf(a);
                        total_payable.setText(result);
                    

    }//GEN-LAST:event_payable_amtKeyReleased

    private void basic_salFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_basic_salFocusLost
        
        if(basic_sal.getText().isEmpty())
                basic_sal.setText("0");
    }//GEN-LAST:event_basic_salFocusLost

    private void pfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_pfKeyTyped

    private void esicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_esicKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_esicKeyTyped

    private void ptKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_ptKeyTyped

    private void other_deductionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_other_deductionKeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_other_deductionKeyTyped

    private void advanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_advanceKeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_advanceKeyTyped

    private void special_deductionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_special_deductionKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_special_deductionKeyTyped

    private void total_attendenceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_attendenceKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_total_attendenceKeyTyped

    private void present_daysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_present_daysKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_present_daysKeyTyped

    private void absent_daysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_absent_daysKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_absent_daysKeyTyped

    private void extra_daysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extra_daysKeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_extra_daysKeyTyped

    private void present_amtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_present_amtKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_present_amtKeyTyped

    private void absent_amtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_absent_amtKeyTyped
      char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_absent_amtKeyTyped

    private void basic_deductionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basic_deductionKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_basic_deductionKeyTyped

    private void total_payableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_payableKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_total_payableKeyTyped

    private void absent_deductionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_absent_deductionKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_absent_deductionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgeSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absent_amt;
    private javax.swing.JTextField absent_days;
    private javax.swing.JTextField absent_deduction;
    private javax.swing.JTextField advance;
    private javax.swing.JTextField basic_deduction;
    private javax.swing.JTextField basic_sal;
    private javax.swing.JTextField basic_sal14;
    private javax.swing.JTextField cca;
    private javax.swing.JTextField conveyance;
    private javax.swing.JTextField esic;
    private javax.swing.JTextField extra_days;
    private javax.swing.JTextField extra_payable;
    private javax.swing.JTextField hra;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField medical_allowance;
    private javax.swing.JTextField other_deduction;
    private javax.swing.JLabel payable_amt;
    private javax.swing.JTextField pf;
    private javax.swing.JTextField present_amt;
    private javax.swing.JTextField present_days;
    private javax.swing.JTextField pt;
    private javax.swing.JTextField regd_id;
    private javax.swing.JTextField regd_id1;
    private javax.swing.JTextField regd_id2;
    private javax.swing.JTextField special_allowance;
    private javax.swing.JTextField special_deduction;
    private javax.swing.JTextField stu_name;
    private javax.swing.JTextField ta_da;
    private javax.swing.JTextField total_attendence;
    private javax.swing.JTextField total_basic_deduction;
    private javax.swing.JTextField total_deduction;
    private javax.swing.JTextField total_payable;
    // End of variables declaration//GEN-END:variables
}
